name: agileoutgoingpredict
services:
  db:
     image: postgres:16.1-alpine3.19
     restart: always
     volumes:
       - /Volumes/Backup3/Docker/agileoutgoingpredict/postgres/pgdata:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - PGUSER=postgres
       - POSTGRES_PASSWORD=postgres
     expose:
       - 5432
     healthcheck:
       test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
       interval: 10s
       timeout: 5s
       retries: 5
  web:
    build: .
    ports:
      - "3011:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - SECRET_KEY=PL88jvUUVO20Vp2R4N7cZUQQ4USaxRGePClEO632rxaJrhbrKf
    depends_on:
      - db
    volumes:
      - .:/code
      - /Volumes/Backup3/Docker/agileoutgoingpredict/static_volume:/code/static
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app-update.schedule: "@every 2h"
      ofelia.job-exec.app-update.command: "python manage.py update"
      ofelia.job-exec.app-update.user: "root"

  scheduler:
    image: mcuadros/ofelia:latest
    depends_on:
      - web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


