# Generated by Django 4.2.11 on 2025-02-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "rename_forecast_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={"ordering": ["date_time"]},
        ),
        migrations.RenameField(
            model_name="pricehistory",
            old_name="agile",
            new_name="agile_outgoing",
        ),
        migrations.AlterField(
            model_name="forecastdata",
            name="agile_incoming",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="forecastdata",
            name="agile_outgoing",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="agile_incoming",
            field=models.FloatField(),
        ),
    ]
