# Generated by Django 4.2.11 on 2025-02-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forecasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(unique=True)),
                ("total_wind", models.FloatField()),
                ("bm_wind", models.FloatField()),
                ("solar", models.FloatField()),
                ("temp_2m", models.FloatField()),
                ("wind_10m", models.FloatField()),
                ("rad", models.FloatField()),
                ("demand", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Nordpool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(unique=True)),
                ("day_ahead", models.FloatField()),
                ("agile", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(unique=True)),
                ("day_ahead", models.FloatField()),
                ("agile", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UpdateErrors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("type", models.CharField(max_length=10)),
                ("dataset", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("day_ahead", models.FloatField()),
                ("day_ahead_incoming", models.FloatField(default=0)),
                ("day_ahead_outgoing", models.FloatField(default=0)),
                ("bm_wind", models.FloatField()),
                ("solar", models.FloatField()),
                ("emb_wind", models.FloatField()),
                ("temp_2m", models.FloatField()),
                ("wind_10m", models.FloatField()),
                ("rad", models.FloatField()),
                ("demand", models.FloatField()),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="prices.forecasts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=1)),
                ("agile_pred", models.FloatField()),
                ("agile_low", models.FloatField()),
                ("agile_high", models.FloatField()),
                ("agile_incoming_pred", models.FloatField(default=0)),
                ("agile_incoming_low", models.FloatField(default=0)),
                ("agile_incoming_high", models.FloatField(default=0)),
                ("date_time", models.DateTimeField()),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="prices.forecasts",
                    ),
                ),
            ],
        ),
    ]
