# Generated by Django 4.2.11 on 2025-02-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="agile_incoming",
            field=models.FloatField(default=0),
        ),
    ]
