# Generated by Django 4.2.11 on 2025-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecasts",
            name="source",
            field=models.CharField(default="", max_length=32),
        ),
    ]
