# Generated by Django 4.2.11 on 2025-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0002_alter_forecasts_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="agiledata",
            name="agile_incoming_high",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="agiledata",
            name="agile_incoming_low",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="agiledata",
            name="agile_incoming_pred",
            field=models.FloatField(default=0),
        ),
    ]
