# Generated by Django 4.2.11 on 2025-02-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0003_forecastdata_day_ahead_high_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecastdata",
            name="day_ahead_high",
        ),
        migrations.RemoveField(
            model_name="forecastdata",
            name="day_ahead_low",
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="agile_incoming",
        ),
    ]
