# Generated by Django 4.2.11 on 2025-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0004_remove_forecastdata_day_ahead_high_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="agile_incoming",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
