# Generated by Django 4.2.11 on 2025-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0005_pricehistory_agile_incoming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="agile_incoming",
            field=models.FloatField(default=0),
        ),
    ]
