sensor:
  - platform: rest
    resource: https://outgoing.shed.gay/api/G
    scan_interval: 3600
    name: Agile Outgoing Predict
    value_template: "{{ value_json[0]['name']}}"
    json_attributes_path: "$[0]"
    json_attributes:
      - "created_at"
      - "prices"

